# Generated by Django 2.0.7 on 2019-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitakorauser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Izena'),
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Abizenak'),
        ),
    ]
