# Generated by Django 2.0.7 on 2019-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191108_1150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bitakorauser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='bitakorauser',
            name='username',
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='googleplus_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='openid_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bitakorauser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-maila'),
        ),
        migrations.AlterField(
            model_name='bitakorauser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bitakorauser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
