# Generated by Django 2.0.7 on 2019-11-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191111_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitakorauser',
            name='usertype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
