# Generated by Django 2.0.7 on 2019-11-11 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bitakorauser_added_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitakorauser',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitakorauser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
