# Generated by Django 2.0.7 on 2019-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191111_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitakorauser',
            name='added_source',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bitakorauser',
            name='usertype',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
