# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('blog', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='external_links', to='base.Blog')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
            },
        ),
    ]
