# Generated by Django 2.0.7 on 2019-11-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ikasbloga', '0005_auto_20191126_1519'),
        ('base', '0003_auto_20191112_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ikasbloga.Room'),
        ),
    ]
