# Generated by Django 2.0.7 on 2019-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikasbloga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=200, null=True, verbose_name='URL'),
        ),
    ]
