# Generated by Django 2.0.7 on 2019-11-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikasbloga', '0003_auto_20191121_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
