# Generated by Django 2.0.7 on 2019-11-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikasbloga', '0004_school_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default=1234, max_length=4, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
